### PR TITLE
Fix CI for kerberos=true

### PR DESCRIPTION
**Pull request by staticmukesh**
Fixed travis build for kerberos enabled hadoop cluster and client.

### CODE REVIEW

**Comment by staticmukesh** [comment]
@Shastick please review my PR.

**Comment by Shastick** [comment]
Thanks! I'll look at this ASAP!

**Comment by staticmukesh** [comment]
Commit has been cherry-picked. So, closing this PR.

**Comment by staticmukesh** [comment]
Commit has been cherry-picked. So, closing this PR.

**Pull request closed without merging**
